### ISSUE TITLE
Instead of providing something where 90% is prebuilt, could you start at the beginning? Just a suggestion. Thanks.

### ISSUE THREAD

**Issue by MrPhilbert** [firebase/friendlyeats-web#10]

**Comment by samtstern** [comment]
@MrPhilbert thank you for the feedback.  We sometimes hear this request, but we've made a conscious choice to have the codelabs start from a "base".  The reason is that we want to each one thing at a time (in this case, Cloud Firestore) without also having to teach all of the prerequisites (html, css, javascript, etc).  We believe that it's too hard to learn all of that at once, so it would actually just make a pretty bad codelab.

If you want to see how an app with Firebase is set up, a good place to look is our quickstarts:
https://github.com/firebase/quickstart-js

These are minimal examples of how to get up and running.
