### ISSUE TITLE
Clicking on Add Mock Ratings shows 400 error responses

### ISSUE THREAD

**Issue by rodrigomata** [firebase/friendlyeats-web#25]
**Error:**

Clicking on Add Mock Ratings shows 400 error responses
<img width="396" alt="screen shot 2018-07-11 at 5 19 14 pm" src="https://user-images.githubusercontent.com/15259836/42602324-94424e7e-852e-11e8-86ab-405642b112b6.png">

**Response:**
`{
  "error": {
    "code": 400,
    "message": "the stored version (1531347069149658) does not match the required base version (1531346493121653)",
    "status": "FAILED_PRECONDITION"
  }
}`

**Image:**

<img width="545" alt="screen shot 2018-07-11 at 5 17 28 pm" src="https://user-images.githubusercontent.com/15259836/42602302-73a157dc-852e-11e8-879a-5f385137cbde.png">

**Steps to reproduce:**

1. Complete codelab
2. Click on a restaurant
3. Click on Mock Review

_EDIT: It only happens when more than 1 review is mocked_

**Comment by axis80** [comment]
I have a related Stack Overflow issue here: https://stackoverflow.com/questions/51814139/firestore-transaction-produces-console-error-failed-precondition-the-stored-ve .  Hopefully a solution on either this issue or that question will lead to a solution on the other one.

**Comment by nicolasgarnier** [comment]
What you are experiencing here is how Transactions work in Firestore: one of the transactions failed to write because the data has changed in the mean time, in this case Firestore re-runs the transaction again, until it succeeds. In the case of multiple Reviews being written at the same time some of them might need to be ran again after the first transaction because the data has changed. This is expected behavior and these errors should be taken more as warnings.

**Comment by Metsuryu** [comment]
@nicolasgarnier is there a way to catch the error and handle it silently, instead of always printing it to the console?
I tried using .catch on the promise, and wrapping everything into a try-catch, but it still always prints the 400 error to the console.
