### ISSUE TITLE
clarify transactions

### ISSUE THREAD

**Issue by sfabriece** [firebase/friendlyeats-web#52]
`Warning: When a transaction fails on the server, the callback is also re-executed repeatedly. Never place logic that modifies app state inside the transaction callback.`

It is not totally clear to me what this warning means. What is referred to as app state?

**Comment by samtstern** [comment]
@sfabriece well this is a **VERY** late response but I'll just answer it anyway.  Sorry this fell through the cracks!

Basically you want to avoid something like this (pseudocode):

```js
// THIS IS APP STATE
let count = 1;

db.runTransaction(function() {
  count++;

  db.ref('foo').set({ ... })
}).then(function() {
   // .. Transaction complete ...
});
```

The reason you want to avoid this is because if we have to retry the transaction, you may see `count = 3` or `count = 5` in your local state due to retries.

Instead you should make sure that the transaction block only deals with Firestore actions, which we can handle appropriately, and that any inputs from your app are constants that won't change in the time it takes to execute.  Handle any app-state changes in the `then`/`catch` block after the transaction is done.

**Comment by sfabriece** [comment]
I was late to notice @samtstern. Thanks for the clarification.
