### ISSUE TITLE
UI for locally served app (FriendlyEats-web) is not as expected

### ISSUE THREAD

**Issue by earnestsaunders** [firebase/friendlyeats-web#65]
![friendlyeats_wonkyui_mainscreen](https://user-images.githubusercontent.com/39200880/53266425-976c6080-3695-11e9-9ffd-83e1782c2c16.png)
![friendlyeats_wonkyui_restaurant](https://user-images.githubusercontent.com/39200880/53266426-976c6080-3695-11e9-848a-d7fd41bf6726.png)

Downloaded the repo for the codelab this morning (Feb 22). https://codelabs.developers.google.com/codelabs/firestore-web

All functionality seems ok as I work through the codelab; it's the UI that's not as expected.  I've run this codelab several times before, and it's not looked like this.

**Comment by samtstern** [comment]
@jhuleatt is gonna take look

**Comment by jhuleatt** [comment]
I'm able to repro this in Chrome if I comment out the line in `index.html` that imports `main.css` ([this line](https://github.com/firebase/friendlyeats-web/blob/master/index.html#L52)).

Based on [this Stack Overflow answer](https://stackoverflow.com/a/9480801/4816918), it looks like we might be missing `type="text/css"` when we import the css file. @earnestsaunders can you please try adding `type="text/css"` to [this `link` tag](https://github.com/firebase/friendlyeats-web/blob/master/index.html#L52) in your project so that it looks like `<link rel="stylesheet" href="/styles/main.css" type="text/css">`, and refresh the page to see if that fixes it? If it does, we can  update the FriendlyEats source.

**Comment by earnestsaunders** [comment]
Yep, after a hard-refresh, it worked!  Thx :-)
